In [1]:
#import libraries

import pandas as pd
import numpy as np

pd.set_option("display.max_columns", None)

In [3]:
# Load the dataset

df = pd.read_csv(r"D:\GIT\data-analytics-portfolio\02-telco-customer-churn\data\raw_data\Telco-Customer-Churn.csv")
df.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,Yes,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,No,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,Yes,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,No,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [4]:
print("Dataframe shape:", df.shape)

Dataframe shape: (7043, 21)

In [5]:
df.dtypes

customerID              str
gender                  str
SeniorCitizen         int64
Partner                 str
Dependents              str
tenure                int64
PhoneService            str
MultipleLines           str
InternetService         str
OnlineSecurity          str
OnlineBackup            str
DeviceProtection        str
TechSupport             str
StreamingTV             str
StreamingMovies         str
Contract                str
PaperlessBilling        str
PaymentMethod           str
MonthlyCharges      float64
TotalCharges            str
Churn                   str
dtype: object

In [7]:
# missing values report

def missing_value_report(df):
    report = pd.DataFrame({
        "missing_count": df.isnull().sum(),
        "missing_percent": round(
            (df.isnull().sum()/len(df))*100,2
        )
    })

    return report.sort_values(
        by="missing_count",
        ascending=False
    )
missing_value_report(df)

                  missing_count  missing_percent
customerID                    0              0.0
gender                        0              0.0
SeniorCitizen                 0              0.0
Partner                       0              0.0
Dependents                    0              0.0
tenure                        0              0.0
PhoneService                  0              0.0
MultipleLines                 0              0.0
InternetService               0              0.0
OnlineSecurity                0              0.0
OnlineBackup                  0              0.0
DeviceProtection              0              0.0
TechSupport                   0              0.0
StreamingTV                   0              0.0
StreamingMovies               0              0.0
Contract                      0              0.0
PaperlessBilling              0              0.0
PaymentMethod                 0              0.0
MonthlyCharges                0              0.0
TotalCharges                  0              0.0
Churn                         0              0.0

In [8]:
(df == " ").sum()

customerID           0
gender               0
SeniorCitizen        0
Partner              0
Dependents           0
tenure               0
PhoneService         0
MultipleLines        0
InternetService      0
OnlineSecurity       0
OnlineBackup         0
DeviceProtection     0
TechSupport          0
StreamingTV          0
StreamingMovies      0
Contract             0
PaperlessBilling     0
PaymentMethod        0
MonthlyCharges       0
TotalCharges        11
Churn                0
dtype: int64

In [9]:
df = df.replace(" ", np.nan)
missing_value_report(df)

                  missing_count  missing_percent
TotalCharges                 11             0.16
gender                        0             0.00
SeniorCitizen                 0             0.00
Partner                       0             0.00
customerID                    0             0.00
Dependents                    0             0.00
tenure                        0             0.00
MultipleLines                 0             0.00
PhoneService                  0             0.00
OnlineSecurity                0             0.00
OnlineBackup                  0             0.00
DeviceProtection              0             0.00
InternetService               0             0.00
TechSupport                   0             0.00
StreamingTV                   0             0.00
Contract                      0             0.00
StreamingMovies               0             0.00
PaperlessBilling              0             0.00
PaymentMethod                 0             0.00
MonthlyCharges                0             0.00
Churn                         0             0.00

In [10]:
# Convert TotalCharges to numeric, forcing errors to NaN

def convert_numeric(df, column):
    df[column] = pd.to_numeric(
        df[column],
        errors="coerce"
    )

    return df

df = convert_numeric(
    df,
    "TotalCharges"
)

In [11]:
df["TotalCharges"].dtype

dtype('float64')

In [12]:
# missing values
missing_value_report(df)

                  missing_count  missing_percent
TotalCharges                 11             0.16
gender                        0             0.00
SeniorCitizen                 0             0.00
Partner                       0             0.00
customerID                    0             0.00
Dependents                    0             0.00
tenure                        0             0.00
MultipleLines                 0             0.00
PhoneService                  0             0.00
OnlineSecurity                0             0.00
OnlineBackup                  0             0.00
DeviceProtection              0             0.00
InternetService               0             0.00
TechSupport                   0             0.00
StreamingTV                   0             0.00
Contract                      0             0.00
StreamingMovies               0             0.00
PaperlessBilling              0             0.00
PaymentMethod                 0             0.00
MonthlyCharges                0             0.00
Churn                         0             0.00

In [13]:
df[df["TotalCharges"].isna()]

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
488,4472-LVYGI,Female,0,Yes,Yes,0,No,No phone service,DSL,Yes,No,Yes,Yes,Yes,No,Two year,Yes,Bank transfer (automatic),52.55,NaN,No
753,3115-CZMZD,Male,0,No,Yes,0,Yes,No,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,20.25,NaN,No
936,5709-LVOEQ,Female,0,Yes,Yes,0,Yes,No,DSL,Yes,Yes,Yes,No,Yes,Yes,Two year,No,Mailed check,80.85,NaN,No
1082,4367-NUYAO,Male,0,Yes,Yes,0,Yes,Yes,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,25.75,NaN,No
1340,1371-DWPAZ,Female,0,Yes,Yes,0,No,No phone service,DSL,Yes,Yes,Yes,Yes,Yes,No,Two year,No,Credit card (automatic),56.05,NaN,No
3331,7644-OMVMY,Male,0,Yes,Yes,0,Yes,No,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,19.85,NaN,No
3826,3213-VVOLG,Male,0,Yes,Yes,0,Yes,Yes,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,25.35,NaN,No
4380,2520-SGTTA,Female,0,Yes,Yes,0,Yes,No,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,20.00,NaN,No
5218,2923-ARZLG,Male,0,Yes,Yes,0,Yes,No,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service,One year,Yes,Mailed check,19.70,NaN,No
6670,4075-WKNIU,Female,0,Yes,Yes,0,Yes,Yes,DSL,No,Yes,Yes,Yes,Yes,No,Two year,No,Mailed check,73.35,NaN,No
6754,2775-SEFEE,Male,0,No,Yes,0,Yes,Yes,DSL,Yes,Yes,No,Yes,No,No,Two year,Yes,Bank transfer (automatic),61.90,NaN,No

In [16]:
# Fill missing values in TotalCharges with 0

df["TotalCharges"] = (
    df["TotalCharges"]
    .fillna(0)
)

In [15]:
missing_value_report(df)

                  missing_count  missing_percent
customerID                    0              0.0
gender                        0              0.0
SeniorCitizen                 0              0.0
Partner                       0              0.0
Dependents                    0              0.0
tenure                        0              0.0
PhoneService                  0              0.0
MultipleLines                 0              0.0
InternetService               0              0.0
OnlineSecurity                0              0.0
OnlineBackup                  0              0.0
DeviceProtection              0              0.0
TechSupport                   0              0.0
StreamingTV                   0              0.0
StreamingMovies               0              0.0
Contract                      0              0.0
PaperlessBilling              0              0.0
PaymentMethod                 0              0.0
MonthlyCharges                0              0.0
TotalCharges                  0              0.0
Churn                         0              0.0

In [17]:
# remove duplicates

def remove_duplicates(df):
    return df.drop_duplicates()

In [19]:
df = remove_duplicates(df)
df.duplicated().sum()

np.int64(0)

In [20]:
#standardize column names

def clean_column_names(df):

    df.columns = (
        df.columns
        .str.strip()
        .str.lower()
        .str.replace(" ", "_")
    )

    return df

df = clean_column_names(df)

In [21]:
df.columns

Index(['customerid', 'gender', 'seniorcitizen', 'partner', 'dependents',
       'tenure', 'phoneservice', 'multiplelines', 'internetservice',
       'onlinesecurity', 'onlinebackup', 'deviceprotection', 'techsupport',
       'streamingtv', 'streamingmovies', 'contract', 'paperlessbilling',
       'paymentmethod', 'monthlycharges', 'totalcharges', 'churn'],
      dtype='str')

In [22]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerid        7043 non-null   str
 1   gender            7043 non-null   str
 2   seniorcitizen     7043 non-null   int64
 3   partner           7043 non-null   str
 4   dependents        7043 non-null   str
 5   tenure            7043 non-null   int64
 6   phoneservice      7043 non-null   str
 7   multiplelines     7043 non-null   str
 8   internetservice   7043 non-null   str
 9   onlinesecurity    7043 non-null   str
 10  onlinebackup      7043 non-null   str
 11  deviceprotection  7043 non-null   str
 12  techsupport       7043 non-null   str
 13  streamingtv       7043 non-null   str
 14  streamingmovies   7043 non-null   str
 15  contract          7043 non-null   str
 16  paperlessbilling  7043 non-null   str
 17  paymentmethod     7043 non-null   str
 18  monthlycharges    7043 non-null   float64
 19  totalcharges      7043 non-null   float64
 20  churn             7043 non-null   str
dtypes: float64(2), int64(2), str(17)
memory usage: 1.1 MB

In [25]:
#target variable distribution
df["churn"].value_counts()

churn
No     5174
Yes    1869
Name: count, dtype: int64

In [27]:
# tenure range
df["tenure"].describe()

count    7043.000000
mean       32.371149
std        24.559481
min         0.000000
25%         9.000000
50%        29.000000
75%        55.000000
max        72.000000
Name: tenure, dtype: float64

In [28]:
df[[
    "monthlycharges",
    "totalcharges"
]].describe()

       monthlycharges  totalcharges
count     7043.000000   7043.000000
mean        64.761692   2279.734304
std         30.090047   2266.794470
min         18.250000      0.000000
25%         35.500000    398.550000
50%         70.350000   1394.550000
75%         89.850000   3786.600000
max        118.750000   8684.800000

In [29]:
print(df.shape)

print(df.isnull().sum().sum())

print(df.duplicated().sum())

(7043, 21)
0
0

In [30]:
df.to_csv(r"D:\GIT\data-analytics-portfolio\02-telco-customer-churn\data\clean_data\telco_customer_churn_cleaned.csv", index=False)