# Data Collection

## Project Objective

This project investigates the relationship between internet penetration, educational attainment, and GDP growth across African countries from 2000–2024.

The objective of this notebook is to:

- Identify relevant World Bank indicators
- Download and load csv file
- Inspect the datasets
- Save raw files for later cleaning and analysis

This notebook forms the data acquisition stage of the analytics workflow.

In [ ]:
import pandas as pd
import wbdata
from datetime import datetime

## Selected Indicators

The following indicators will be used:

| Variable | World Bank Indicator |
|-----------|---------------------|
| GDP Growth (%) | NY.GDP.MKTP.KD.ZG |
| Internet Usage (% Population) | IT.NET.USER.ZS |
| School Enrollment, Secondary (%) | SE.SEC.ENRR |

In [ ]:
 # Define Indicators
 
indicators = {
 "NY.GDP.MKTP.KD.ZG": "gdp_growth", 
 "IT.NET.USER.ZS": "internet_users", 
 "SE.SEC.ENRR": "secondary_enrollment" 
 }

## Time Period

The study covers African countries between 2000 and 2024.

In [ ]:
dates = (
    datetime(2000, 1, 1),
    datetime(2024, 12, 31)
)

# Extract start and end years for World Bank API queries
#start_year = dates[0].year
#end_year = dates[1].year

In [6]:
import pandas as pd

wdi = pd.read_csv(r"D:\GIT\data-analytics-portfolio\01-world-bank-analysis\data\raw_data\WDI_CSV\WDICSV.csv")
country = pd.read_csv(r"D:\GIT\data-analytics-portfolio\01-world-bank-analysis\data\raw_data\WDI_CSV\WDICountry.csv")
series = pd.read_csv(r"D:\GIT\data-analytics-portfolio\01-world-bank-analysis\data\raw_data\WDI_CSV\WDISeries.csv")
country_series = pd.read_csv(r"D:\GIT\data-analytics-portfolio\01-world-bank-analysis\data\raw_data\WDI_CSV\WDIcountry-series.csv")
series_time = pd.read_csv(r"D:\GIT\data-analytics-portfolio\01-world-bank-analysis\data\raw_data\WDI_CSV\WDIseries-time.csv")
footnote = pd.read_csv(r"D:\GIT\data-analytics-portfolio\01-world-bank-analysis\data\raw_data\WDI_CSV\WDIfootnote.csv")

In [12]:
wdi.head()

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025
0,Africa Eastern and Southern,AFE,Access to clean fuels and technologies for coo...,EG.CFT.ACCS.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,18.685118,19.205632,19.742772,20.332679,20.862800,21.419621,21.996456,22.541440,NaN,NaN
1,Africa Eastern and Southern,AFE,Access to clean fuels and technologies for coo...,EG.CFT.ACCS.RU.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,7.606712,7.926604,8.309896,8.704591,9.106640,9.480804,9.903209,10.288154,NaN,NaN
2,Africa Eastern and Southern,AFE,Access to clean fuels and technologies for coo...,EG.CFT.ACCS.UR.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,39.052626,39.321068,39.649534,39.968299,40.354628,40.723805,41.026351,41.289974,NaN,NaN
3,Africa Eastern and Southern,AFE,Access to electricity (% of population),EG.ELC.ACCS.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,38.859598,40.223744,43.035073,44.390861,46.282371,48.127211,48.742043,50.667516,52.598171,NaN
4,Africa Eastern and Southern,AFE,"Access to electricity, rural (% of rural popul...",EG.ELC.ACCS.RU.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,24.584906,25.375037,26.941984,28.983183,30.909991,32.709837,33.998179,35.240236,36.080572,NaN

In [10]:
series.head()

,Series Code,Topic,Indicator Name,Short definition,Long definition,Unit of measure,Periodicity,Base Period,Other notes,Aggregation method,Limitations and exceptions,Notes from original source,General comments,Source,Statistical concept and methodology,Development relevance,Related source links,Other web links,Related indicators,License Type
0,AG.CON.FERT.PT.ZS,Environment: Agricultural production,Fertilizer consumption (% of fertilizer produc...,NaN,Fertilizer consumption measures the quantity o...,% (ratio),Annual,NaN,The world and regional aggregate series do not...,Weighted average,The FAO has revised the time series for fertil...,NaN,NaN,"FAO electronic files and web site, Food and Ag...",Methodology: Fertilizer consumption measures t...,"Factors, such as the green revolution, have le...",NaN,NaN,NaN,CC BY-4.0
1,AG.CON.FERT.ZS,Environment: Agricultural production,Fertilizer consumption (kilograms per hectare ...,NaN,Fertilizer consumption measures the quantity o...,kg per hectare of arable land,Annual,NaN,The world and regional aggregate series do not...,Weighted average,The FAO has revised the time series for fertil...,NaN,NaN,"FAO electronic files and web site, Food and Ag...",Methodology: Fertilizer consumption measures t...,"Factors, such as the green revolution, have le...",NaN,NaN,NaN,CC BY-4.0
2,AG.LND.AGRI.K2,Environment: Land use,Agricultural land (sq. km),NaN,Agricultural land refers to the land area that...,square kilometers (sq. km),Annual,NaN,Areas of former states are included in the suc...,Sum,The data are collected by the Food and Agricul...,NaN,NaN,"FAO electronic files and web site, Food and Ag...",Methodology: Agricultural land constitutes onl...,Agricultural land covers more than one-third o...,NaN,NaN,NaN,CC BY-4.0
3,AG.LND.AGRI.ZS,Environment: Land use,Agricultural land (% of land area),NaN,Agricultural land refers to the share of land ...,% (share) of land area,Annual,NaN,Areas of former states are included in the suc...,Weighted average,The data are collected by the Food and Agricul...,NaN,NaN,"FAO electronic files and web site, Food and Ag...",Methodology: Agriculture is still a major sect...,Agricultural land covers more than one-third o...,NaN,NaN,NaN,CC BY-4.0
4,AG.LND.ARBL.HA,Environment: Land use,Arable land (hectares),NaN,Arable land (in hectares) includes land define...,hectares,Annual,NaN,Areas of former states are included in the suc...,NaN,The Food and Agriculture Organization (FAO) tr...,NaN,NaN,"FAO electronic files and web site, Food and Ag...",Methodology: Temporary fallow land refers to l...,Agricultural land covers more than one-third o...,NaN,NaN,NaN,CC BY-4.0

In [11]:
country.head()

,Country Code,Short Name,Table Name,Long Name,2-alpha code,Currency Unit,Special Notes,Region,Income Group,WB-2 code,...,Government Accounting concept,IMF data dissemination standard,Latest population census,Latest household survey,Source of most recent Income and expenditure data,Vital registration complete,Latest agricultural census,Latest industrial data,Latest trade data,Latest water withdrawal data
0,ABW,Aruba,Aruba,Aruba,AW,Aruban florin,NaN,Latin America & Caribbean,High income,AW,...,NaN,Enhanced General Data Dissemination System (e-...,2020 (expected),NaN,NaN,Yes,NaN,NaN,2018.0,NaN
1,AFE,Africa Eastern and Southern,Africa Eastern and Southern,Africa Eastern and Southern,ZH,NaN,"26 countries, stretching from the Red Sea in t...",NaN,NaN,ZH,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,AFG,Afghanistan,Afghanistan,Islamic State of Afghanistan,AF,Afghan afghani,The reporting period for national accounts dat...,Middle East & North Africa,Low income,AF,...,Consolidated central government,Enhanced General Data Dissemination System (e-...,1979,Multiple Indicator Cluster Survey 2022-2023,"Integrated household survey (IHS), 2016/17",NaN,2003.0,NaN,2018.0,NaN
3,AFW,Africa Western and Central,Africa Western and Central,Africa Western and Central,ZI,NaN,"22 countries, stretching from the westernmost ...",NaN,NaN,ZI,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,AGO,Angola,Angola,People's Republic of Angola,AO,Angolan kwanza,The World Bank systematically assesses the app...,Sub-Saharan Africa,Lower middle income,AO,...,Budgetary central government,Enhanced General Data Dissemination System (e-...,2014,Inquérito de Indicadores Múltiplos e de Saúde ...,"Integrated household survey (IHS), 2008/09",NaN,2023.0,NaN,2018.0,NaN

In [13]:
df = pd.merge(
    wdi,
    country, 
    how='left', 
    left_on='Country Code', 
    right_on='Country Code'
    )

df = pd.merge(
    df, 
    series, 
    how='left', 
    left_on='Indicator Code', 
    right_on='Series Code'
    )

In [16]:
df.shape
df.head()

,Country Name,Country Code,Indicator Name_x,Indicator Code,1960,1961,1962,1963,1964,1965,...,Limitations and exceptions,Notes from original source,General comments,Source,Statistical concept and methodology,Development relevance,Related source links,Other web links,Related indicators,License Type
0,Africa Eastern and Southern,AFE,Access to clean fuels and technologies for coo...,EG.CFT.ACCS.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,"Tracking SDG 7: The Energy Progress Report, AC...",Methodology: Data for access to clean fuels an...,NaN,NaN,NaN,NaN,CC BY-4.0
1,Africa Eastern and Southern,AFE,Access to clean fuels and technologies for coo...,EG.CFT.ACCS.RU.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,"Tracking SDG 7: The Energy Progress Report, In...",Methodology: Data for access to clean fuels an...,NaN,NaN,NaN,NaN,CC BY-4.0
2,Africa Eastern and Southern,AFE,Access to clean fuels and technologies for coo...,EG.CFT.ACCS.UR.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,"Tracking SDG 7: The Energy Progress Report, In...",Methodology: Data for access to clean fuels an...,NaN,NaN,NaN,NaN,CC BY-4.0
3,Africa Eastern and Southern,AFE,Access to electricity (% of population),EG.ELC.ACCS.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,"SDG 7.1.1 Electrification Dataset, World Bank ...",Methodology: The World Bank’s Global Electrifi...,Maintaining reliable and secure electricity se...,NaN,NaN,NaN,CC BY-4.0
4,Africa Eastern and Southern,AFE,"Access to electricity, rural (% of rural popul...",EG.ELC.ACCS.RU.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,"SDG 7.1.1 Electrification Dataset, World Bank ...",Methodology: The World Bank’s Global Electrifi...,Maintaining reliable and secure electricity se...,NaN,NaN,NaN,CC BY-4.0

In [18]:
df.to_csv(r"D:\GIT\data-analytics-portfolio\01-world-bank-analysis\data\raw_data\world_bank_data.csv", index=False)

In [19]:
df.isnull().sum()

Country Name                  0
Country Code                  0
Indicator Name_x              0
Indicator Code                0
1960                     359744
                          ...
Development relevance     48495
Related source links     396970
Other web links          396970
Related indicators       396970
License Type                  0
Length: 120, dtype: int64

In [ ]:
# year columns to remove
cols_to_drop = [str(year) for year in range(1960, 2000)]
df = df.drop(columns=cols_to_drop)
df.head()

,Country Name,Country Code,Indicator Name_x,Indicator Code,2000,2001,2002,2003,2004,2005,...,Limitations and exceptions,Notes from original source,General comments,Source,Statistical concept and methodology,Development relevance,Related source links,Other web links,Related indicators,License Type
0,Africa Eastern and Southern,AFE,Access to clean fuels and technologies for coo...,EG.CFT.ACCS.ZS,11.494704,11.841055,12.202523,12.573380,12.958690,13.371142,...,NaN,NaN,NaN,"Tracking SDG 7: The Energy Progress Report, AC...",Methodology: Data for access to clean fuels an...,NaN,NaN,NaN,NaN,CC BY-4.0
1,Africa Eastern and Southern,AFE,Access to clean fuels and technologies for coo...,EG.CFT.ACCS.RU.ZS,3.548167,3.704024,3.890043,4.091720,4.274249,4.532521,...,NaN,NaN,NaN,"Tracking SDG 7: The Energy Progress Report, In...",Methodology: Data for access to clean fuels an...,NaN,NaN,NaN,NaN,CC BY-4.0
2,Africa Eastern and Southern,AFE,Access to clean fuels and technologies for coo...,EG.CFT.ACCS.UR.ZS,32.350689,32.683340,33.100177,33.490465,33.991183,34.470608,...,NaN,NaN,NaN,"Tracking SDG 7: The Energy Progress Report, In...",Methodology: Data for access to clean fuels an...,NaN,NaN,NaN,NaN,CC BY-4.0
3,Africa Eastern and Southern,AFE,Access to electricity (% of population),EG.ELC.ACCS.ZS,19.917256,19.944277,21.548647,22.493217,23.724455,23.449539,...,NaN,NaN,NaN,"SDG 7.1.1 Electrification Dataset, World Bank ...",Methodology: The World Bank’s Global Electrifi...,Maintaining reliable and secure electricity se...,NaN,NaN,NaN,CC BY-4.0
4,Africa Eastern and Southern,AFE,"Access to electricity, rural (% of rural popul...",EG.ELC.ACCS.RU.ZS,8.672653,NaN,NaN,9.792811,10.890979,10.336474,...,NaN,NaN,NaN,"SDG 7.1.1 Electrification Dataset, World Bank ...",Methodology: The World Bank’s Global Electrifi...,Maintaining reliable and secure electricity se...,NaN,NaN,NaN,CC BY-4.0

In [23]:
df[["Country Code", "Region"]].head()

  Country Code Region
0          AFE    NaN
1          AFE    NaN
2          AFE    NaN
3          AFE    NaN
4          AFE    NaN

## Filter African Countries

The World Bank dataset contains all countries and regions.

For this project, only African countries will be retained.

In [25]:
africa = [
    "Kenya","Uganda","Tanzania","Rwanda","Burundi",
    "South Sudan","Ethiopia","Somalia","Djibouti","Eritrea",
    "Nigeria","Ghana","South Africa","Egypt","Morocco",
    "Algeria","Tunisia","Libya","Sudan","Cameroon",
    "Senegal","Zambia","Zimbabwe","Botswana","Namibia",
    "Mozambique","Malawi","Madagascar","Mauritius","Seychelles",
    "Angola","Benin","Burkina Faso","Cape Verde",
    "Central African Republic","Chad","Comoros",
    "Republic of the Congo","DR Congo","Equatorial Guinea",
    "Gabon","Gambia","Guinea","Guinea-Bissau",
    "Ivory Coast","Lesotho","Liberia","Mali",
    "Mauritania","Niger","Sao Tome and Principe",
    "Sierra Leone","Eswatini","Togo"
]

In [26]:
df_africa = df[df["Short Name"].isin(africa)]

print(df_africa.shape)

df_africa.head()

(68908, 80)

,Country Name,Country Code,Indicator Name_x,Indicator Code,2000,2001,2002,2003,2004,2005,...,Limitations and exceptions,Notes from original source,General comments,Source,Statistical concept and methodology,Development relevance,Related source links,Other web links,Related indicators,License Type
74900,Algeria,DZA,Access to clean fuels and technologies for coo...,EG.CFT.ACCS.ZS,96.5,97.0,97.45,97.8,98.1,98.4,...,NaN,NaN,NaN,"Tracking SDG 7: The Energy Progress Report, AC...",Methodology: Data for access to clean fuels an...,NaN,NaN,NaN,NaN,CC BY-4.0
74901,Algeria,DZA,Access to clean fuels and technologies for coo...,EG.CFT.ACCS.RU.ZS,92.6,93.4,94.10,94.8,95.4,95.9,...,NaN,NaN,NaN,"Tracking SDG 7: The Energy Progress Report, In...",Methodology: Data for access to clean fuels an...,NaN,NaN,NaN,NaN,CC BY-4.0
74902,Algeria,DZA,Access to clean fuels and technologies for coo...,EG.CFT.ACCS.UR.ZS,99.6,99.7,99.80,99.8,99.9,99.9,...,NaN,NaN,NaN,"Tracking SDG 7: The Energy Progress Report, In...",Methodology: Data for access to clean fuels an...,NaN,NaN,NaN,NaN,CC BY-4.0
74903,Algeria,DZA,Access to electricity (% of population),EG.ELC.ACCS.ZS,98.6,98.6,98.60,98.6,98.6,98.6,...,NaN,NaN,NaN,"SDG 7.1.1 Electrification Dataset, World Bank ...",Methodology: The World Bank’s Global Electrifi...,Maintaining reliable and secure electricity se...,NaN,NaN,NaN,CC BY-4.0
74904,Algeria,DZA,"Access to electricity, rural (% of rural popul...",EG.ELC.ACCS.RU.ZS,97.4,97.4,97.40,97.4,97.4,97.4,...,NaN,NaN,NaN,"SDG 7.1.1 Electrification Dataset, World Bank ...",Methodology: The World Bank’s Global Electrifi...,Maintaining reliable and secure electricity se...,NaN,NaN,NaN,CC BY-4.0

In [31]:
#Rename column "Indicator Namex" to "Indicator Name" to avoid confusion with the other "Indicator Name" column in the merged dataframe
df_africa = df_africa.rename(columns={"Indicator Name_x": "Indicator Name"})

In [32]:
# Checking if the selected indicators are present in the dataset

selected_indicators = [
    "NY.GDP.MKTP.KD.ZG",  # GDP growth (annual %)
    "IT.NET.USER.ZS",     # Internet users (per 100 people)
    "SE.SEC.ENRR"         # Secondary school enrollment (% gross)
]
df_africa[df_africa["Indicator Code"]
          .isin(selected_indicators)][["Indicator Code", "Indicator Name"]].drop_duplicates()

          Indicator Code                                    Indicator Name
75414  NY.GDP.MKTP.KD.ZG                             GDP growth (annual %)
75562     IT.NET.USER.ZS  Individuals using the Internet (% of population)
76181        SE.SEC.ENRR            School enrollment, secondary (% gross)

In [33]:
print(df_africa.columns.tolist())

['Country Name', 'Country Code', 'Indicator Name', 'Indicator Code', '2000', '2001', '2002', '2003', '2004', '2005', '2006', '2007', '2008', '2009', '2010', '2011', '2012', '2013', '2014', '2015', '2016', '2017', '2018', '2019', '2020', '2021', '2022', '2023', '2024', '2025', 'Short Name', 'Table Name', 'Long Name', '2-alpha code', 'Currency Unit', 'Special Notes', 'Region', 'Income Group', 'WB-2 code', 'National accounts base year', 'National accounts reference year', 'SNA price valuation', 'Lending category', 'Other groups', 'System of National Accounts', 'Alternative conversion factor', 'PPP survey year', 'Balance of Payments Manual in use', 'External debt Reporting status', 'System of trade', 'Government Accounting concept', 'IMF data dissemination standard', 'Latest population census', 'Latest household survey', 'Source of most recent Income and expenditure data', 'Vital registration complete', 'Latest agricultural census', 'Latest industrial data', 'Latest trade data', 'Latest water withdrawal data', 'Series Code', 'Topic', 'Indicator Name_y', 'Short definition', 'Long definition', 'Unit of measure', 'Periodicity', 'Base Period', 'Other notes', 'Aggregation method', 'Limitations and exceptions', 'Notes from original source', 'General comments', 'Source', 'Statistical concept and methodology', 'Development relevance', 'Related source links', 'Other web links', 'Related indicators', 'License Type']

In [35]:
df_africa[df_africa["Indicator Code"]
          .isin(selected_indicators)].groupby(["Indicator Name"]).size().reset_index(name='count')

                                     Indicator Name  count
0                             GDP growth (annual %)     46
1  Individuals using the Internet (% of population)     46
2            School enrollment, secondary (% gross)     46

In [38]:
years = [str(year) for year in range(2000, 2025)]
indicator_data = df_africa[df_africa["Indicator Code"].isin(selected_indicators)]
indicator_data[years].isnull().mean() * 100  # Calculate percentage of missing values for each year

2000    12.318841
2001    10.144928
2002    10.144928
2003    15.217391
2004    13.043478
2005    13.043478
2006    14.492754
2007    15.217391
2008    16.666667
2009    16.666667
2010    17.391304
2011    10.869565
2012    15.942029
2013    16.666667
2014    14.492754
2015    12.318841
2016    15.942029
2017    17.391304
2018    21.739130
2019    22.463768
2020    25.362319
2021    23.188406
2022    26.811594
2023    25.362319
2024    28.260870
dtype: float64

In [39]:
df_africa.shape

(68908, 80)

In [40]:
df_africa.to_csv(r"D:\GIT\data-analytics-portfolio\01-world-bank-analysis\data\raw_data\africa_data.csv", index=False)

## Notebook Summary

In this notebook:

✓ Selected World Bank indicators

✓ Retrieved data using pd.read_csv

✓ Inspected dataset structure

✓ Filtered African countries

✓ Investigated if the selected indicators are present in the dataset

✓ Investigated missing values to determine if the dataset can be used for analysis

✓ Saved raw datasets for cleaning

The next notebook will focus on data cleaning and preparation.